logging:
  level:
    org.springframework: info

spring:
  messages:
    basename: messages
  security:
    user:
      name: ridao
      password: password
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
